### ISSUE TITLE
Same Timestamp read twice when storing data from a Bagfile

### ISSUE THREAD

**Issue by Surxz** [RoboSherlock/robosherlock#94] opened 2017-07-18 14:17 UTC
When running the storage pipeline with a Bagfile I frequently get two images in a row which have the same timestamp. This leads to the cameraInfo being deleted in Line 399 of the Storage.cpp. Since the cameraInfo is only being written in the first run, I end up with a database without cameraInfo. I checked the timestamp in Line 383 in Storage.cpp and it does exist in my database, so it seems like the CollectionReader is reading the same image twice. A quick fix i did was to change Line 396 to the following:
`      if(name[0] != '_' && !(name.find("camera_info") == 0))
`
That way the camera info never gets deleted and i end up with a working database, but this doesn't fix the issue.

**Comment by bbferka** [comment] 2017-07-19 11:25
Thx for the report. At first glance this looks like a bug in CollectionReader, that I am unable to reproduce so far on my machine.

**Comment by bbferka** [comment] 2017-10-10 15:42
@Surxz do you think you could give this a quick try?

**Comment by Surxz** [comment] 2017-10-10 17:07
@bbferka tested this and it works for me.

**Comment by bbferka** [comment] 2017-10-10 22:06
thx, closing this isse and merging #101

**Closed by bbferka** 2017-10-10 22:06 UTC
Labels: bug
